#!/bin/bash
ruby run.rb
git add .
git commit -a -m 'generating static files'
git push && \
git checkout gh-pages && \

git checkout master -- public/* && \
rm *.html
rm -rf assets
cp -Rf public/* .
git commit -m "syncing gh-pages branch to master" && \
git push && \
git checkout master
